// src/components/settings/tab.ai.vue
<script setup lang="ts">
import { computed } from 'vue';
import { AppSettings } from '../../types';

const props = defineProps<{
  localSettings: AppSettings;
  isManualModelInput: boolean;
  connectionStatus: Record<string, string>;
  connectionBusy: Record<string, boolean>;
  promptEditors: Array<{ key: keyof AppSettings; label: string }>;
}>();

const emit = defineEmits<{
  (e: 'update:localSettings', value: AppSettings): void;
  (e: 'toggle-manual-model'): void;
  (e: 'test-ai'): void;
  (e: 'restore-prompt', key: keyof AppSettings): void;
  (e: 'restore-all-prompts'): void;
}>();

const localSettings = computed({
  get: () => props.localSettings,
  set: (val) => emit('update:localSettings', val),
});
</script>

<template>
  <div class="space-y-3.5">
    <div class="space-y-2">
      <label class="flex items-center justify-between cursor-pointer">
        <span class="font-bold text-slate-200">✨ Enable AI Assistant Features:</span>
        <input type="checkbox" v-model="localSettings.enableAI" class="accent-teal-500 w-4 h-4 cursor-pointer" />
      </label>
    </div>

    <div class="space-y-2 pt-2 border-t border-dark-border/60">
      <label class="flex items-center justify-between cursor-pointer">
        <div>
          <span class="font-bold text-slate-200 block">⚡ Enable AI Preload (Background Pre-fetch):</span>
          <span class="text-xs text-slate-400 block">After Dictionary lookup finishes, load Main AI first, then Context, Grammar, and the other intents in the background.</span>
        </div>
        <input type="checkbox" v-model="localSettings.enableAiPreload" class="accent-teal-500 w-4 h-4 cursor-pointer flex-shrink-0 ml-2" />
      </label>
    </div>

    <div class="space-y-2 pt-2 border-t border-dark-border/60">
      <label class="flex items-center justify-between cursor-pointer">
        <div>
          <span class="font-bold text-slate-200 block">💬 Use AI when a phrase has no dictionary definition:</span>
          <span class="text-xs text-slate-400 block">Only runs when AI is enabled. Explains idioms dictionary backends miss.</span>
        </div>
        <input type="checkbox" v-model="localSettings.enablePhraseFallback" class="accent-teal-500 w-4 h-4 cursor-pointer flex-shrink-0 ml-2" />
      </label>
    </div>

    <!-- Gemini API Key Section -->
    <div class="space-y-2 pt-2 border-t border-dark-border/60">
      <label class="font-bold text-slate-200 block flex items-center justify-between">
        <span>🔑 Google Gemini API Key:</span>
        <a
          href="https://aistudio.google.com/app/apikey"
          target="_blank"
          class="text-xs text-teal-400 hover:underline flex items-center gap-1"
        >
          <span>Get Free API Key ↗</span>
        </a>
      </label>

      <input
        v-model="localSettings.aiApiKey"
        type="password"
        placeholder="Paste API Key (AIzaSy...)"
        class="w-full bg-dark-muted border border-dark-border rounded-xl px-3 py-2 text-sm text-slate-100 placeholder-slate-500 outline-none focus:border-teal-500 transition-all font-mono"
      />
      <p class="text-xs text-slate-400 leading-normal">
        Stored only on this device in `chrome.storage.local`. It is not synced and is never exported. Leave blank to keep the current key.
      </p>
    </div>

    <!-- AI Model Dual Mode Selection -->
    <div class="space-y-2 pt-2 border-t border-dark-border/60">
      <div class="flex items-center justify-between">
        <label class="font-bold text-slate-200">🤖 AI Model (Gemini Model):</label>

        <button
          type="button"
          @click="emit('toggle-manual-model')"
          class="text-xs px-2 py-0.5 rounded bg-dark-muted hover:bg-dark-border text-teal-400 font-bold border border-dark-border transition-colors cursor-pointer"
        >
          {{ isManualModelInput ? '📋 Preset List' : '✏️ Custom Model ID' }}
        </button>
      </div>

      <!-- Preset Dropdown Mode -->
      <select
        v-if="!isManualModelInput"
        v-model="localSettings.aiModel"
        class="w-full bg-dark-muted border border-dark-border text-slate-200 text-sm font-medium rounded-xl px-3 py-2 outline-none focus:border-teal-500 cursor-pointer"
      >
        <option value="gemini-2.5-flash">⚡ gemini-2.5-flash (Recommended - Fast &amp; Smart)</option>
        <option value="gemini-3.5-flash-lite">🚀 gemini-3.5-flash-lite (Maximum Speed)</option>
        <option value="gemini-1.5-flash">✨ gemini-1.5-flash (Standard Baseline)</option>
        <option value="gemini-1.5-pro">🧠 gemini-1.5-pro (Deep Analysis)</option>
      </select>

      <!-- Manual Write-in Mode -->
      <input
        v-else
        v-model="localSettings.aiModel"
        type="text"
        placeholder="Enter custom Gemini model ID (e.g. gemini-2.5-pro)..."
        class="w-full bg-dark-muted border border-dark-border rounded-xl px-3 py-2 text-sm text-slate-100 placeholder-slate-500 outline-none focus:border-teal-500 transition-all font-mono"
      />
    </div>

    <div class="space-y-2 pt-2 border-t border-dark-border/60">
      <label class="font-bold text-slate-200 block">🔗 Custom AI Base URL (Optional Endpoint):</label>
      <input
        v-model="localSettings.aiBaseUrl"
        type="text"
        placeholder="https://generativelanguage.googleapis.com"
        class="w-full bg-dark-muted border border-dark-border rounded-xl px-3 py-2 text-sm text-slate-100 placeholder-slate-500 outline-none focus:border-teal-500 transition-all font-mono"
      />
      <p class="text-xs text-slate-400">Gemini URLs use generateContent. Any other URL is treated as OpenAI-compatible /chat/completions.</p>
      <div class="flex items-center gap-2">
        <button
          type="button"
          class="px-2.5 py-1.5 rounded-lg bg-dark-muted border border-dark-border text-sm font-bold text-slate-200 hover:border-teal-500 cursor-pointer"
          :disabled="connectionBusy.ai"
          @click="emit('test-ai')"
        >
          Test AI connection
        </button>
        <span class="text-xs text-slate-400">{{ connectionStatus.ai }}</span>
      </div>
    </div>

    <div class="space-y-3 pt-2 border-t border-dark-border/60">
      <div class="flex items-center justify-between">
        <label class="font-bold text-slate-200">📝 Prompt templates</label>
        <button
          type="button"
          class="text-xs px-2 py-0.5 rounded bg-dark-muted hover:bg-dark-border text-teal-400 font-bold border border-dark-border cursor-pointer"
          @click="emit('restore-all-prompts')"
        >
          Restore all defaults
        </button>
      </div>
      <p class="text-xs text-slate-400">Variables: <code v-pre>{{str}}</code>, <code v-pre>{{text}}</code>, <code v-pre>{{sentence}}</code>, <code v-pre>{{context}}</code>, <code v-pre>{{targetLang}}</code>, <code v-pre>{{word_count}}</code></p>
      <div v-for="editor in promptEditors" :key="editor.key" class="space-y-1.5">
        <div class="flex items-center justify-between">
          <span class="text-sm font-bold text-slate-300">{{ editor.label }}</span>
          <button
            type="button"
            class="text-xs text-teal-400 font-bold cursor-pointer"
            @click="emit('restore-prompt', editor.key)"
          >
            Restore default
          </button>
        </div>
        <textarea
          v-model="(localSettings as any)[editor.key]"
          rows="5"
          class="w-full bg-dark-muted border border-dark-border rounded-xl px-3 py-2 text-sm text-slate-100 placeholder-slate-500 outline-none focus:border-teal-500 font-mono"
        ></textarea>
      </div>
    </div>
  </div>
</template>

// src/features/settings/tabs/TabAi.tsx
import React from 'react';
import { AppSettings } from '@/types';
import { cx } from '@/ui/cx';
import { IconEdit, IconExternalLink, IconSparkles, IconSpinner } from '@/components/icons';
import {
  DEFAULT_GEMINI_BASE_URL,
  DEFAULT_GEMINI_MODEL,
  DEFAULT_OPENAI_BASE_URL,
  isOpenAiStandard,
} from '@/shared/settings';

interface TabAiProps {
  localSettings: AppSettings;
  isManualModelInput: boolean;
  connectionStatus: Record<string, string>;
  connectionBusy: Record<string, boolean>;
  promptEditors: Array<{ key: keyof AppSettings; label: string }>;
  onChange: (patch: Partial<AppSettings>) => void;
  onToggleManualModel: () => void;
  onTestAi: () => void;
  onRestorePrompt: (promptKey: keyof AppSettings) => void;
  onRestoreAllPrompts: () => void;
}

export const TabAi: React.FC<TabAiProps> = ({
  localSettings,
  isManualModelInput,
  connectionStatus,
  connectionBusy,
  promptEditors,
  onChange,
  onToggleManualModel,
  onTestAi,
  onRestorePrompt,
  onRestoreAllPrompts,
}) => {
  const isOpenAi = isOpenAiStandard(localSettings);

  return (
    <div className="space-y-4 font-sans text-xs">
      {/* Enable AI Assistant */}
      <div className="space-y-2">
        <label className="flex items-center justify-between cursor-pointer p-2 rounded-xl hover:bg-muted transition-colors">
          <div>
            <span className="font-bold text-content block text-xs">
              Enable AI Assistant &amp; Smart Analysis
            </span>
            <span className="text-[11px] text-content-muted block">
              Contextual analysis, grammar nuance, breakdown, and confusable comparison
            </span>
          </div>
          <input
            type="checkbox"
            checked={localSettings.enableAI !== false}
            onChange={(e) => onChange({ enableAI: e.target.checked })}
            className="accent-teal-500 dark:accent-gold-400 w-4 h-4 cursor-pointer"
          />
        </label>
      </div>

      {/* AI Preload Background */}
      <div className="space-y-2 pt-2 border-t border-border/60">
        <label className="flex items-center justify-between cursor-pointer p-2 rounded-xl hover:bg-muted transition-colors">
          <div>
            <span className="font-bold text-content block text-xs">
              Background AI Preload on Text Selection
            </span>
            <span className="text-[11px] text-content-muted block">
              Pre-fetches explanations when text is highlighted so results appear instantly
            </span>
          </div>
          <input
            type="checkbox"
            checked={Boolean(localSettings.enableAiPreload)}
            onChange={(e) => onChange({ enableAiPreload: e.target.checked })}
            className="accent-teal-500 dark:accent-gold-400 w-4 h-4 cursor-pointer"
          />
        </label>
      </div>

      {/* Phrase Fallback */}
      <div className="space-y-2 pt-2 border-t border-border/60">
        <label className="flex items-center justify-between cursor-pointer p-2 rounded-xl hover:bg-muted transition-colors">
          <div>
            <span className="font-bold text-content block text-xs">
              Use AI when a phrase has no dictionary definition
            </span>
            <span className="text-[11px] text-content-muted block">
              Automatically provides AI explanations for idioms and multi-word phrases
            </span>
          </div>
          <input
            type="checkbox"
            checked={Boolean(localSettings.enablePhraseFallback)}
            onChange={(e) => onChange({ enablePhraseFallback: e.target.checked })}
            className="accent-teal-500 dark:accent-gold-400 w-4 h-4 cursor-pointer"
          />
        </label>
      </div>

      {/* Provider Selector: Gemini vs OpenAI Standard */}
      <div className="space-y-2 pt-3 border-t border-border/60">
        <label className="font-bold text-content-secondary uppercase tracking-wider text-[11px] block">
          AI Provider Engine
        </label>
        <div className="grid grid-cols-2 gap-2 p-1 bg-muted rounded-xl border border-border">
          <button
            type="button"
            onClick={() => {
              onChange({
                aiProvider: 'gemini',
                aiModel: DEFAULT_GEMINI_MODEL,
                aiBaseUrl: DEFAULT_GEMINI_BASE_URL,
              });
            }}
            className={cx(
              'py-2 px-3 rounded-lg text-xs font-bold transition-all flex items-center justify-center gap-1.5 cursor-pointer',
              !isOpenAi
                ? 'bg-surface text-teal-700 dark:text-gold-200 border border-border shadow-xs'
                : 'text-content-muted hover:text-content',
            )}
          >
            <span>Google Gemini</span>
            <span className="text-[10px] opacity-75 font-normal">(Default)</span>
          </button>
          <button
            type="button"
            onClick={() => {
              onChange({
                aiProvider: 'openai',
                aiModel: '',
                aiBaseUrl: DEFAULT_OPENAI_BASE_URL,
              });
            }}
            className={cx(
              'py-2 px-3 rounded-lg text-xs font-bold transition-all flex items-center justify-center gap-1.5 cursor-pointer',
              isOpenAi
                ? 'bg-surface text-teal-700 dark:text-gold-200 border border-border shadow-xs'
                : 'text-content-muted hover:text-content',
            )}
          >
            <span>OpenAI Standard</span>
            <span className="text-[10px] opacity-75 font-normal">(Ollama, etc.)</span>
          </button>
        </div>
      </div>

      {/* OpenAI Standard Base URL */}
      {isOpenAi && (
        <div className="space-y-2 pt-2 border-t border-border/60">
          <div className="flex items-center justify-between">
            <label className="font-bold text-content-secondary uppercase tracking-wider text-[11px]">
              API Base URL (OpenAI Standard)
            </label>
            <span className="text-[10px] text-content-muted">
              POST /chat/completions
            </span>
          </div>
          <input
            value={localSettings.aiBaseUrl || DEFAULT_OPENAI_BASE_URL}
            onChange={(e) => onChange({ aiBaseUrl: e.target.value })}
            type="text"
            placeholder={DEFAULT_OPENAI_BASE_URL}
            className="w-full bg-muted border border-border rounded-xl px-3 py-2 text-xs text-content placeholder:text-content-muted outline-none focus:border-teal-500 dark:focus:border-gold-300 font-mono shadow-xs"
          />
          <div className="flex flex-wrap gap-1.5 pt-0.5">
            {[
              [DEFAULT_OPENAI_BASE_URL, 'Default (localhost:20128)'],
              ['http://localhost:11434/v1', 'Ollama (localhost:11434)'],
              ['https://api.openai.com/v1', 'ChatGPT (OpenAI)'],
            ].map(([url, label]) => (
              <button
                key={url}
                type="button"
                onClick={() => onChange({ aiBaseUrl: url })}
                className="text-[10px] px-2 py-0.5 rounded-md bg-muted hover:bg-elevated border border-border text-content-secondary hover:text-teal-600 dark:hover:text-gold-200 font-mono cursor-pointer transition-colors"
              >
                {label}
              </button>
            ))}
          </div>
        </div>
      )}

      {/* API Key */}
      <div className="space-y-2 pt-2 border-t border-border/60">
        <div className="flex items-center justify-between">
          <label className="font-bold text-content-secondary uppercase tracking-wider text-[11px]">
            {isOpenAi ? 'API Key (Optional for Local / Ollama)' : 'Google Gemini API Key'}
          </label>
          {!isOpenAi && (
            <a
              href="https://aistudio.google.com/app/apikey"
              target="_blank"
              rel="noreferrer"
              className="text-xs text-teal-600 dark:text-gold-300 hover:underline flex items-center gap-1 font-semibold"
            >
              <span>Get Free Key</span>
              <IconExternalLink className="w-3 h-3" />
            </a>
          )}
        </div>

        <input
          value={localSettings.aiApiKey || ''}
          onChange={(e) => onChange({ aiApiKey: e.target.value })}
          type="password"
          placeholder={isOpenAi ? 'sk-... (leave blank for local Ollama / proxy)' : 'Paste Gemini API Key (AIzaSy...)'}
          className="w-full bg-muted border border-border rounded-xl px-3 py-2.5 text-xs text-content placeholder:text-content-muted outline-none focus:border-teal-500 dark:focus:border-gold-300 font-mono shadow-xs"
        />
        <p className="text-[11px] text-content-muted">
          {isOpenAi
            ? 'Stored locally on this device. Leave blank if your local OpenAI server or Ollama does not require an API key.'
            : 'Stored locally on this device via Chrome secure storage. Never exported in backups.'}
        </p>
      </div>

      {/* Model Selection */}
      <div className="space-y-2 pt-2 border-t border-border/60">
        <div className="flex items-center justify-between">
          <label className="font-bold text-content-secondary uppercase tracking-wider text-[11px]">
            {isOpenAi ? 'OpenAI Model' : 'Gemini Model'}
          </label>
          {!isOpenAi && (
            <button
              type="button"
              onClick={onToggleManualModel}
              className="text-[11px] px-2.5 py-1 rounded-lg bg-muted hover:bg-elevated text-teal-600 dark:text-gold-300 dark:hover:text-gold-200 font-semibold border border-border cursor-pointer transition-colors"
            >
              {isManualModelInput ? 'Select Presets' : 'Custom Model ID'}
            </button>
          )}
        </div>

        {isOpenAi || isManualModelInput ? (
          <input
            value={localSettings.aiModel || ''}
            onChange={(e) => onChange({ aiModel: e.target.value })}
            type="text"
            placeholder={isOpenAi ? 'Model name as required by your server' : 'Enter custom Gemini model ID (e.g. gemini-3.5-flash-lite)...'}
            className="w-full bg-muted border border-border rounded-xl px-3 py-2 text-xs text-content placeholder:text-content-muted outline-none focus:border-teal-500 dark:focus:border-gold-300 font-mono shadow-xs"
          />
        ) : (
          <select
            value={localSettings.aiModel || DEFAULT_GEMINI_MODEL}
            onChange={(e) => onChange({ aiModel: e.target.value })}
            className="w-full bg-muted border border-border text-content text-xs font-medium rounded-xl px-3 py-2.5 outline-none focus:border-teal-500 dark:focus:border-gold-300 cursor-pointer shadow-xs"
          >
            <option value={DEFAULT_GEMINI_MODEL} className="bg-surface text-content">{DEFAULT_GEMINI_MODEL} (Recommended · Ultra Fast &amp; Smart)</option>
          </select>
        )}
      </div>

      {/* Test Connection Button */}
      <div className="pt-2 border-t border-border/60">
        <div className="flex items-center gap-2">
          <button
            type="button"
            className="px-3 py-1.5 rounded-lg bg-muted hover:bg-elevated border border-border text-xs font-semibold text-content-secondary hover:text-teal-600 dark:hover:text-gold-200 cursor-pointer shadow-xs flex items-center gap-1.5 active:scale-95"
            disabled={connectionBusy.ai}
            onClick={onTestAi}
          >
            {connectionBusy.ai ? <IconSpinner className="w-3.5 h-3.5 text-teal-500 dark:text-gold-300" /> : <IconSparkles className="w-3.5 h-3.5 text-teal-500 dark:text-gold-300" />}
            <span>Test {isOpenAi ? 'OpenAI' : 'Gemini'} Connection</span>
          </button>
          {connectionStatus.ai && (
            <span className="text-[11px] px-2 py-0.5 rounded-md bg-muted border border-border text-teal-600 dark:text-gold-300 font-mono">
              {connectionStatus.ai}
            </span>
          )}
        </div>
      </div>

      {/* Prompt Templates */}
      <div className="space-y-3 pt-3 border-t border-border/60">
        <div className="flex items-center justify-between">
          <label className="font-bold text-content-secondary uppercase tracking-wider text-[11px]">
            Prompt Templates
          </label>
          <button
            type="button"
            className="text-[11px] px-2.5 py-1 rounded-lg bg-muted hover:bg-elevated text-teal-600 dark:text-gold-300 dark:hover:text-gold-200 font-semibold border border-border cursor-pointer transition-colors"
            onClick={onRestoreAllPrompts}
          >
            Reset All Prompts
          </button>
        </div>

        <div className="space-y-3">
          {promptEditors.map(({ key, label }) => (
            <div key={key} className="p-3 rounded-xl border border-border bg-surface space-y-2 shadow-xs">
              <div className="flex items-center justify-between">
                <span className="font-bold text-content text-xs flex items-center gap-1.5">
                  <IconEdit className="w-3.5 h-3.5 text-teal-600 dark:text-gold-300" />
                  <span>{label}</span>
                </span>
                <button
                  type="button"
                  onClick={() => onRestorePrompt(key)}
                  className="text-[10px] text-content-muted hover:text-teal-600 dark:hover:text-gold-200 underline cursor-pointer"
                >
                  Restore default
                </button>
              </div>
              <textarea
                value={String(localSettings[key] || '')}
                onChange={(e) => onChange({ [key]: e.target.value })}
                rows={4}
                className="w-full bg-muted border border-border rounded-lg p-2.5 text-xs text-content font-mono outline-none focus:border-teal-500 dark:focus:border-gold-300 leading-relaxed"
              />
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default TabAi;
