// src/components/card.collocations.vue
<script setup lang="ts">
import { computed } from 'vue';
import { Collocations } from '../types';

const props = defineProps<{
  word?: string;
  collocations?: Collocations;
}>();

const emit = defineEmits<{
  (e: 'select-word', word: string): void;
}>();

const calculatedCollocations = computed<Collocations>(() => {
  if (props.collocations && (
    props.collocations.verbs?.length ||
    props.collocations.nouns?.length ||
    props.collocations.adjectives?.length ||
    props.collocations.prepositions?.length ||
    props.collocations.patterns?.length
  )) {
    return props.collocations;
  }

  // Return empty collocations if no real API data exists so card cleanly hides
  return {};
});

const hasAnyData = computed(() => {
  const c = calculatedCollocations.value;
  return Boolean(
    c.verbs?.length ||
    c.nouns?.length ||
    c.adjectives?.length ||
    c.prepositions?.length ||
    c.patterns?.length
  );
});
</script>

<template>
  <div v-if="hasAnyData" class="pt-3 border-t border-dark-border/50 space-y-2.5">
    <div class="flex items-center gap-1.5 text-[11px] font-extrabold text-teal-400 uppercase tracking-wider">
      <span>🔗</span>
      <span>COLLOCATIONS</span>
    </div>

    <div class="space-y-2 text-xs">
      <div v-if="calculatedCollocations.verbs?.length" class="space-y-1">
        <span class="text-slate-400 font-semibold text-[11px] block">Common Verbs</span>
        <div class="flex flex-wrap gap-1.5">
          <button
            v-for="item in calculatedCollocations.verbs"
            :key="item"
            @click="emit('select-word', item)"
            class="px-2.5 py-0.5 rounded-full bg-dark-muted hover:bg-teal-500/20 hover:text-teal-300 text-teal-300 text-[11px] transition-all cursor-pointer font-medium"
          >
            {{ item }}
          </button>
        </div>
      </div>

      <div v-if="calculatedCollocations.nouns?.length" class="space-y-1">
        <span class="text-slate-400 font-semibold text-[11px] block">Common Nouns</span>
        <div class="flex flex-wrap gap-1.5">
          <button
            v-for="item in calculatedCollocations.nouns"
            :key="item"
            @click="emit('select-word', item)"
            class="px-2.5 py-0.5 rounded-full bg-dark-muted hover:bg-teal-500/20 hover:text-teal-300 text-teal-300 text-[11px] transition-all cursor-pointer font-medium"
          >
            {{ item }}
          </button>
        </div>
      </div>

      <div v-if="calculatedCollocations.patterns?.length" class="space-y-1">
        <span class="text-slate-400 font-semibold text-[11px] block">Patterns</span>
        <div class="flex flex-wrap gap-1.5">
          <button
            v-for="item in calculatedCollocations.patterns"
            :key="item"
            @click="emit('select-word', item)"
            class="px-2.5 py-0.5 rounded-full bg-dark-muted hover:bg-teal-500/20 hover:text-teal-300 text-teal-300 text-[11px] transition-all cursor-pointer font-medium"
          >
            {{ item }}
          </button>
        </div>
      </div>

      <div v-if="calculatedCollocations.prepositions?.length" class="space-y-1">
        <span class="text-slate-400 font-semibold text-[11px] block">Prepositions</span>
        <div class="flex flex-wrap gap-1.5">
          <button
            v-for="item in calculatedCollocations.prepositions"
            :key="item"
            @click="emit('select-word', item)"
            class="px-2.5 py-0.5 rounded-full bg-dark-muted hover:bg-teal-500/20 hover:text-teal-300 text-teal-300 text-[11px] transition-all cursor-pointer font-medium"
          >
            {{ item }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

// src/components/card.collocations.tsx
import React, { useMemo } from 'react';
import { Collocations } from '../types';

interface CollocationsCardProps {
  word?: string;
  collocations?: Collocations;
  onSelectWord?: (word: string) => void;
}

const chipClass =
  'px-2.5 py-0.5 rounded-full bg-dark-muted hover:bg-teal-500/20 hover:text-teal-300 text-teal-300 text-[11px] transition-all cursor-pointer font-medium';

export const CollocationsCard: React.FC<CollocationsCardProps> = ({
  collocations,
  onSelectWord,
}) => {
  const calculatedCollocations = useMemo<Collocations>(() => {
    if (
      collocations &&
      (collocations.verbs?.length ||
        collocations.nouns?.length ||
        collocations.adjectives?.length ||
        collocations.prepositions?.length ||
        collocations.patterns?.length)
    ) {
      return collocations;
    }
    return {};
  }, [collocations]);

  const hasAnyData = Boolean(
    calculatedCollocations.verbs?.length ||
      calculatedCollocations.nouns?.length ||
      calculatedCollocations.adjectives?.length ||
      calculatedCollocations.prepositions?.length ||
      calculatedCollocations.patterns?.length,
  );

  if (!hasAnyData) return null;

  const renderChips = (items?: string[]) =>
    items?.map((item) => (
      <button key={item} type="button" onClick={() => onSelectWord?.(item)} className={chipClass}>
        {item}
      </button>
    ));

  return (
    <div className="pt-3 border-t border-dark-border/50 space-y-2.5">
      <div className="flex items-center gap-1.5 text-[11px] font-extrabold text-teal-400 uppercase tracking-wider">
        <span>🔗</span>
        <span>COLLOCATIONS</span>
      </div>

      <div className="space-y-2 text-xs">
        {calculatedCollocations.verbs?.length ? (
          <div className="space-y-1">
            <span className="text-slate-400 font-semibold text-[11px] block">Common Verbs</span>
            <div className="flex flex-wrap gap-1.5">{renderChips(calculatedCollocations.verbs)}</div>
          </div>
        ) : null}

        {calculatedCollocations.nouns?.length ? (
          <div className="space-y-1">
            <span className="text-slate-400 font-semibold text-[11px] block">Common Nouns</span>
            <div className="flex flex-wrap gap-1.5">{renderChips(calculatedCollocations.nouns)}</div>
          </div>
        ) : null}

        {calculatedCollocations.patterns?.length ? (
          <div className="space-y-1">
            <span className="text-slate-400 font-semibold text-[11px] block">Patterns</span>
            <div className="flex flex-wrap gap-1.5">{renderChips(calculatedCollocations.patterns)}</div>
          </div>
        ) : null}

        {calculatedCollocations.prepositions?.length ? (
          <div className="space-y-1">
            <span className="text-slate-400 font-semibold text-[11px] block">Prepositions</span>
            <div className="flex flex-wrap gap-1.5">{renderChips(calculatedCollocations.prepositions)}</div>
          </div>
        ) : null}
      </div>
    </div>
  );
};

export default CollocationsCard;
