// src/components/card.ai-lexical-extras.tsx
import React, { Suspense, useMemo } from 'react';
import { lexicalExtrasForIntent } from '../shared/ai-prompts';
import { LexicalProfile } from '../types';
import {
  CollocationsCard,
  LearnerMistakesCard,
  UsageNotesCard,
  WordFamilyCard,
  WordFormationCard,
} from './async-views';

interface AiLexicalExtrasProps {
  query?: string;
  profile?: LexicalProfile;
  intent?: string;
  onSelectWord?: (word: string) => void;
}

export const AiLexicalExtras: React.FC<AiLexicalExtrasProps> = ({
  query,
  profile,
  intent,
  onSelectWord,
}) => {
  const extras = useMemo(() => new Set(lexicalExtrasForIntent(intent)), [intent]);

  const formation = useMemo(() => {
    const value = profile?.wordFormation;
    if (!value) return { text: '', prefixes: [] as string[], suffixes: [] as string[] };
    if (typeof value === 'string') return { text: value, prefixes: [], suffixes: [] };
    return {
      text: value.explanation || '',
      prefixes: value.prefixes || [],
      suffixes: value.suffixes || [],
    };
  }, [profile]);

  return (
    <Suspense fallback={null}>
      {extras.has('wordFamily') ? (
        <WordFamilyCard word={query} family={profile?.wordFamily} onSelectWord={onSelectWord} />
      ) : null}
      {extras.has('usageNotes') ? (
        <UsageNotesCard warnings={profile?.usageWarnings} pairs={profile?.confusablePairs} />
      ) : null}
      {extras.has('wordFormation') ? (
        <WordFormationCard
          formation={formation.text}
          prefixes={formation.prefixes}
          suffixes={formation.suffixes}
        />
      ) : null}
      {extras.has('learnerMistakes') ? (
        <LearnerMistakesCard mistakes={profile?.learnerMistakes} />
      ) : null}
      {extras.has('collocations') ? (
        <CollocationsCard
          word={query}
          collocations={profile?.collocations}
          onSelectWord={onSelectWord}
        />
      ) : null}
    </Suspense>
  );
};

export default AiLexicalExtras;

// src/components/card.ai-lexical-extras.vue
<script setup lang="ts">
import { computed } from 'vue';
import { lexicalExtrasForIntent } from '../shared/ai-prompts';
import { LexicalProfile } from '../types';
import {
  CollocationsCard,
  LearnerMistakesCard,
  UsageNotesCard,
  WordFamilyCard,
  WordFormationCard,
} from './async-views';

const props = defineProps<{
  query?: string;
  profile?: LexicalProfile;
  intent?: string;
}>();

const emit = defineEmits<{
  (e: 'select-word', word: string): void;
}>();

const extras = computed(() => new Set(lexicalExtrasForIntent(props.intent)));

const formation = computed(() => {
  const value = props.profile?.wordFormation;
  if (!value) return { text: '', prefixes: [] as string[], suffixes: [] as string[] };
  if (typeof value === 'string') return { text: value, prefixes: [], suffixes: [] };
  return {
    text: value.explanation || '',
    prefixes: value.prefixes || [],
    suffixes: value.suffixes || [],
  };
});
</script>

<template>
  <WordFamilyCard
    v-if="extras.has('wordFamily')"
    :word="query"
    :family="profile?.wordFamily"
    @select-word="emit('select-word', $event)"
  />
  <UsageNotesCard
    v-if="extras.has('usageNotes')"
    :warnings="profile?.usageWarnings"
    :pairs="profile?.confusablePairs"
  />
  <WordFormationCard
    v-if="extras.has('wordFormation')"
    :formation="formation.text"
    :prefixes="formation.prefixes"
    :suffixes="formation.suffixes"
  />
  <LearnerMistakesCard
    v-if="extras.has('learnerMistakes')"
    :mistakes="profile?.learnerMistakes"
  />
  <CollocationsCard
    v-if="extras.has('collocations')"
    :word="query"
    :collocations="profile?.collocations"
    @select-word="emit('select-word', $event)"
  />
</template>
