// src/components/intent.ai-markdown.vue
<script setup lang="ts">
import { AiResult } from '../types';
import MarkdownRenderer from './component.markdown-renderer.vue';
import AiLexicalExtras from './card.ai-lexical-extras.vue';

defineProps<{
  result: AiResult;
  targetLang?: string;
}>();

const emit = defineEmits<{
  (e: 'select-word', word: string): void;
}>();
</script>

<template>
  <div class="space-y-4">
    <div v-if="result.summary" class="pt-2 border-t border-dark-border/50 space-y-3">
      <MarkdownRenderer :content="result.summary" :target-lang="targetLang" />
    </div>
    <AiLexicalExtras
      :query="result.query"
      :profile="result.lexicalProfile"
      :intent="result.type"
      @select-word="emit('select-word', $event)"
    />
  </div>
</template>

// src/components/intent.ai-markdown.tsx
import React from 'react';
import { AiResult } from '../types';
import MarkdownRenderer from './component.markdown-renderer';
import AiLexicalExtras from './card.ai-lexical-extras';

interface AiMarkdownIntentProps {
  result: AiResult;
  targetLang?: string;
  onSelectWord?: (word: string) => void;
}

export const AiMarkdownIntent: React.FC<AiMarkdownIntentProps> = ({
  result,
  targetLang,
  onSelectWord,
}) => {
  return (
    <div className="space-y-4">
      {result.summary ? (
        <div className="pt-2 border-t border-dark-border/50 space-y-3">
          <MarkdownRenderer content={result.summary} targetLang={targetLang} />
        </div>
      ) : null}
      <AiLexicalExtras
        query={result.query}
        profile={result.lexicalProfile}
        intent={result.type}
        onSelectWord={onSelectWord}
      />
    </div>
  );
};

export default AiMarkdownIntent;
