// src/features/settings/tabs/TabSources.tsx
import React from 'react';
import { AppSettings } from '@/types';
import { IconBook, IconSpeaker, IconSpinner, IconTranslate } from '@/components/icons';

interface TabSourcesProps {
  localSettings: AppSettings;
  languageOptions: string[];
  connectionStatus: Record<string, string>;
  connectionBusy: Record<string, boolean>;
  availableVoices: SpeechSynthesisVoice[];
  onChange: (patch: Partial<AppSettings>) => void;
  onTestTranslation: () => void;
  onTestDictionary: (providerId: string) => void;
}

export const TabSources: React.FC<TabSourcesProps> = ({
  localSettings,
  languageOptions,
  connectionStatus,
  connectionBusy,
  availableVoices,
  onChange,
  onTestTranslation,
  onTestDictionary,
}) => {
  const translationKey = `translation:${localSettings.translateProvider || 'google'}`;
  const lastDictStatus =
    connectionStatus[localSettings.dictionaryProvider] ||
    Object.entries(connectionStatus)
      .filter(([key]) => !key.startsWith('translation:') && key !== 'ai')
      .map(([, value]) => value)
      .slice(-1)[0];

  return (
    <div className="space-y-4 font-sans text-xs">
      {/* Toggles */}
      <div className="space-y-2">
        <label className="flex items-center justify-between cursor-pointer p-2 rounded-xl hover:bg-muted transition-colors">
          <div>
            <span className="font-bold text-content block text-xs">Show Translation in Dictionary View</span>
            <span className="text-[11px] text-content-muted block">Displays instant localized translation above meanings</span>
          </div>
          <input
            type="checkbox"
            checked={localSettings.enableTranslate !== false}
            onChange={(e) => onChange({ enableTranslate: e.target.checked })}
            className="accent-teal-500 w-4 h-4 cursor-pointer"
          />
        </label>
        <label className="flex items-center justify-between cursor-pointer p-2 rounded-xl hover:bg-muted transition-colors">
          <div>
            <span className="font-bold text-content block text-xs">Show Definitions in Dictionary View</span>
            <span className="text-[11px] text-content-muted block">Displays full dictionary definition cards and word senses</span>
          </div>
          <input
            type="checkbox"
            checked={localSettings.enableDictionary !== false}
            onChange={(e) => onChange({ enableDictionary: e.target.checked })}
            className="accent-teal-500 w-4 h-4 cursor-pointer"
          />
        </label>
      </div>

      {/* Target language */}
      <div className="space-y-2 pt-3 border-t border-border/60">
        <label className="font-bold text-content-secondary block uppercase tracking-wider text-[11px]">
          Default Target Translation Language
        </label>
        <select
          value={localSettings.translateTargetLanguage || 'Vietnamese'}
          onChange={(e) => onChange({ translateTargetLanguage: e.target.value })}
          className="w-full bg-muted border border-border text-content text-xs font-medium rounded-xl px-3 py-2.5 outline-none focus:border-teal-500 cursor-pointer shadow-xs"
        >
          {languageOptions.map((lang) => (
            <option key={lang} value={lang} className="bg-surface text-content">
              {lang}
            </option>
          ))}
        </select>
      </div>

      {/* Custom languages */}
      <div className="space-y-2 pt-3 border-t border-border/60">
        <label className="font-bold text-content-secondary block uppercase tracking-wider text-[11px]">
          Custom Language List
        </label>
        <input
          value={localSettings.customLanguages || ''}
          onChange={(e) => onChange({ customLanguages: e.target.value })}
          type="text"
          placeholder="Vietnamese, English, Japanese, French"
          className="w-full bg-muted border border-border rounded-xl px-3 py-2 text-xs text-content placeholder:text-content-muted outline-none focus:border-teal-500 shadow-xs"
        />
      </div>

      {/* Translation Provider */}
      <div className="space-y-2 pt-3 border-t border-border/60">
        <label className="font-bold text-content-secondary block uppercase tracking-wider text-[11px]">
          Translation Engine Provider
        </label>
        <select
          value={localSettings.translateProvider || 'google'}
          onChange={(e) => onChange({ translateProvider: e.target.value as AppSettings['translateProvider'] })}
          className="w-full bg-muted border border-border text-content text-xs font-medium rounded-xl px-3 py-2.5 outline-none focus:border-teal-500 cursor-pointer shadow-xs"
        >
          <option value="google" className="bg-surface text-content">Google Translate (Default)</option>
          <option value="libretranslate" className="bg-surface text-content">LibreTranslate</option>
          <option value="mymemory" className="bg-surface text-content">MyMemory (Keyless fallback)</option>
        </select>
        <div className="flex items-center gap-2 pt-1">
          <button
            type="button"
            className="px-3 py-1.5 rounded-lg bg-muted hover:bg-elevated border border-border text-xs font-semibold text-content-secondary hover:text-teal-600 dark:hover:text-teal-300 cursor-pointer shadow-xs flex items-center gap-1.5"
            disabled={connectionBusy[translationKey]}
            onClick={onTestTranslation}
          >
            {connectionBusy[translationKey] ? <IconSpinner className="w-3.5 h-3.5 text-teal-500 dark:text-teal-400" /> : <IconTranslate className="w-3.5 h-3.5 text-teal-500 dark:text-teal-400" />}
            <span>Test Translation Connection</span>
          </button>
          {connectionStatus[translationKey] && (
            <span className="text-[11px] px-2 py-0.5 rounded-md bg-muted border border-border text-teal-600 dark:text-teal-300 font-mono">
              {connectionStatus[translationKey]}
            </span>
          )}
        </div>
      </div>

      {/* Dictionary Provider */}
      <div className="space-y-2 pt-3 border-t border-border/60">
        <label className="font-bold text-content-secondary block uppercase tracking-wider text-[11px]">
          Default Dictionary Provider
        </label>
        <select
          value={localSettings.dictionaryProvider || 'wiktionary'}
          onChange={(e) =>
            onChange({ dictionaryProvider: e.target.value as AppSettings['dictionaryProvider'] })
          }
          className="w-full bg-muted border border-border text-content text-xs font-medium rounded-xl px-3 py-2.5 outline-none focus:border-teal-500 cursor-pointer shadow-xs"
        >
          <option value="wiktionary" className="bg-surface text-content">Wiktionary Open API (Default)</option>
          <option value="free_dictionary" className="bg-surface text-content">Free Dictionary API</option>
          <option value="datamuse" className="bg-surface text-content">Datamuse (Keyless collocations)</option>
          <option value="wikipedia" className="bg-surface text-content">Wikipedia Summary</option>
          <option value="urban_dictionary" className="bg-surface text-content">Urban Dictionary (Slang &amp; Idioms)</option>
          <option value="google_translate" className="bg-surface text-content">Google Translate API</option>
        </select>
      </div>

      {/* Test Dictionary Connection */}
      <div className="space-y-2 pt-3 border-t border-border/60">
        <label className="font-bold text-content-secondary block uppercase tracking-wider text-[11px]">
          Test Dictionary Connectivity
        </label>
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
          {(
            [
              ['wiktionary', 'Wiktionary'],
              ['free_dictionary', 'Free Dictionary'],
              ['datamuse', 'Datamuse'],
              ['wikipedia', 'Wikipedia'],
              ['urban_dictionary', 'Urban Dictionary'],
              ['rhymebrain', 'RhymeBrain'],
            ] as const
          ).map(([id, label]) => (
            <button
              key={id}
              type="button"
              className="px-2.5 py-1.5 rounded-lg bg-muted hover:bg-elevated border border-border text-xs font-semibold text-content-secondary hover:text-teal-600 dark:hover:text-teal-300 cursor-pointer shadow-xs flex items-center justify-center gap-1 active:scale-95"
              disabled={connectionBusy[id]}
              onClick={() => onTestDictionary(id)}
            >
              {connectionBusy[id] ? <IconSpinner className="w-3 h-3 text-teal-500 dark:text-teal-400" /> : <IconBook className="w-3 h-3 text-teal-500 dark:text-teal-400" />}
              <span>{label}</span>
            </button>
          ))}
        </div>
        {lastDictStatus ? (
          <p className="text-[11px] text-teal-600 dark:text-teal-300/90 font-mono mt-1">{lastDictStatus}</p>
        ) : null}
      </div>

      {/* Voice & Speech Synthesis */}
      <div className="space-y-2 pt-3 border-t border-border/60">
        <label className="font-bold text-content-secondary block uppercase tracking-wider text-[11px] flex items-center gap-1.5">
          <IconSpeaker className="w-3.5 h-3.5 text-teal-500 dark:text-teal-400" />
          <span>Speech Synthesis (TTS Voice)</span>
        </label>
        <select
          value={localSettings.pronunciationVoiceURI || ''}
          onChange={(e) => onChange({ pronunciationVoiceURI: e.target.value })}
          className="w-full bg-muted border border-border text-content text-xs font-medium rounded-xl px-3 py-2.5 outline-none focus:border-teal-500 cursor-pointer shadow-xs"
        >
          <option value="" className="bg-surface text-content">Auto-select system default voice</option>
          {availableVoices.map((voice) => (
            <option key={voice.voiceURI} value={voice.voiceURI} className="bg-surface text-content">
              {voice.name} ({voice.lang})
            </option>
          ))}
        </select>

        <div className="pt-2">
          <div className="flex items-center justify-between gap-3 bg-muted/40 p-2.5 rounded-xl border border-border">
            <div>
              <span className="text-content font-semibold text-xs block">Pronunciation Speech Rate:</span>
              <span className="text-[11px] text-content-muted">Controls playback speed of speech synthesis</span>
            </div>
            <div className="flex items-center gap-2">
              <input
                type="range"
                min="0.5"
                max="1.5"
                step="0.05"
                value={localSettings.pronunciationRate ?? 1}
                onChange={(e) => onChange({ pronunciationRate: parseFloat(e.target.value) })}
                className="accent-teal-500 cursor-pointer w-28"
              />
              <span className="font-mono text-teal-600 dark:text-teal-300 text-xs w-10 text-right">
                {localSettings.pronunciationRate ?? 1}x
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TabSources;

// src/components/settings/tab.sources.vue
<script setup lang="ts">
import { computed } from 'vue';
import { AppSettings } from '../../types';

const props = defineProps<{
  localSettings: AppSettings;
  languageOptions: string[];
  connectionStatus: Record<string, string>;
  connectionBusy: Record<string, boolean>;
  availableVoices: SpeechSynthesisVoice[];
}>();

const emit = defineEmits<{
  (e: 'update:localSettings', value: AppSettings): void;
  (e: 'test-translation'): void;
  (e: 'test-dictionary', providerId: string): void;
}>();

const localSettings = computed({
  get: () => props.localSettings,
  set: (val) => emit('update:localSettings', val),
});
</script>

<template>
  <div class="space-y-3.5">
    <div class="space-y-2">
      <label class="flex items-center justify-between cursor-pointer">
        <span class="font-bold text-slate-200">🌐 Show translation in Dictionary tab:</span>
        <input type="checkbox" v-model="localSettings.enableTranslate" class="accent-teal-500 w-4 h-4 cursor-pointer" />
      </label>
      <label class="flex items-center justify-between cursor-pointer">
        <span class="font-bold text-slate-200">📖 Show definitions in Dictionary tab:</span>
        <input type="checkbox" v-model="localSettings.enableDictionary" class="accent-teal-500 w-4 h-4 cursor-pointer" />
      </label>
    </div>

    <div class="space-y-2 pt-2 border-t border-dark-border/60">
      <label class="font-bold text-slate-200 block">🌐 Default Target Translation Language:</label>
      <select
        v-model="localSettings.translateTargetLanguage"
        class="w-full bg-dark-muted border border-dark-border text-slate-200 text-sm font-medium rounded-xl px-3 py-2 outline-none focus:border-teal-500 cursor-pointer"
      >
        <option v-for="lang in languageOptions" :key="lang" :value="lang">{{ lang }}</option>
      </select>
    </div>

    <div class="space-y-2 pt-2 border-t border-dark-border/60">
      <label class="font-bold text-slate-200 block">📝 Custom language list:</label>
      <input
        v-model="localSettings.customLanguages"
        type="text"
        placeholder="Vietnamese, English, Japanese"
        class="w-full bg-dark-muted border border-dark-border rounded-xl px-3 py-2 text-sm text-slate-100 placeholder-slate-500 outline-none focus:border-teal-500"
      />
    </div>

    <div class="space-y-2 pt-2 border-t border-dark-border/60">
      <label class="font-bold text-slate-200 block">🌍 Translation provider:</label>
      <select
        v-model="localSettings.translateProvider"
        class="w-full bg-dark-muted border border-dark-border text-slate-200 text-sm font-medium rounded-xl px-3 py-2 outline-none focus:border-teal-500 cursor-pointer"
      >
        <option value="google">Google Translate</option>
        <option value="libretranslate">LibreTranslate</option>
      </select>
      <div class="flex items-center gap-2">
        <button
          type="button"
          class="px-2.5 py-1.5 rounded-lg bg-dark-muted border border-dark-border text-sm font-bold text-slate-200 hover:border-teal-500 cursor-pointer"
          :disabled="connectionBusy[`translation:${localSettings.translateProvider}`]"
          @click="emit('test-translation')"
        >
          Test translation
        </button>
        <span class="text-xs text-slate-400">{{ connectionStatus[`translation:${localSettings.translateProvider}`] }}</span>
      </div>
    </div>

    <div v-if="localSettings.translateProvider === 'libretranslate'" class="space-y-2 pt-2 border-t border-dark-border/60">
      <label class="font-bold text-slate-200 block">LibreTranslate base URL:</label>
      <input
        v-model="localSettings.libreTranslateBaseUrl"
        type="url"
        placeholder="https://libretranslate.com"
        class="w-full bg-dark-muted border border-dark-border rounded-xl px-3 py-2 text-sm text-slate-100 placeholder-slate-500 outline-none focus:border-teal-500 font-mono"
      />
      <label class="font-bold text-slate-200 block">LibreTranslate API key (optional):</label>
      <input
        v-model="localSettings.libreTranslateApiKey"
        type="password"
        placeholder="LibreTranslate API key"
        class="w-full bg-dark-muted border border-dark-border rounded-xl px-3 py-2 text-sm text-slate-100 placeholder-slate-500 outline-none focus:border-teal-500 font-mono"
      />
    </div>

    <div class="space-y-2 pt-2 border-t border-dark-border/60">
      <label class="font-bold text-slate-200 block">📚 Default Dictionary Provider:</label>
      <select
        v-model="localSettings.dictionaryProvider"
        class="w-full bg-dark-muted border border-dark-border text-slate-200 text-sm font-medium rounded-xl px-3 py-2 outline-none focus:border-teal-500 cursor-pointer"
      >
        <option value="free_dictionary">🌐 Free Dictionary API (Google Baseline)</option>
        <option value="google_translate">🌐 Google Translate API</option>
        <option value="wiktionary">📖 Wiktionary Open API</option>
        <option value="merriam_webster">🏛️ Merriam-Webster Learner API</option>
        <option value="wordnik">📚 Wordnik Dictionary API</option>
        <option value="words_api">⚡ WordsAPI (RapidAPI)</option>
      </select>
    </div>

    <div class="space-y-2 pt-2 border-t border-dark-border/60">
      <label class="font-bold text-slate-200 block">🔑 Merriam-Webster API Key (Optional):</label>
      <input
        v-model="localSettings.dictionaryApiKey"
        type="password"
        placeholder="MW Collegiate API key"
        class="w-full bg-dark-muted border border-dark-border rounded-xl px-3 py-2 text-sm text-slate-100 placeholder-slate-500 outline-none focus:border-teal-500 font-mono"
      />
      <p class="text-xs text-slate-400">Free key from dictionaryapi.com. Required only for Merriam-Webster.</p>
    </div>

    <div class="space-y-2 pt-2 border-t border-dark-border/60">
      <label class="font-bold text-slate-200 block">🔑 Wordnik API Key (Optional):</label>
      <input
        v-model="localSettings.wordnikApiKey"
        type="password"
        placeholder="Wordnik API Key..."
        class="w-full bg-dark-muted border border-dark-border rounded-xl px-3 py-2 text-sm text-slate-100 placeholder-slate-500 outline-none focus:border-teal-500 font-mono"
      />
    </div>

    <div class="space-y-2 pt-2 border-t border-dark-border/60">
      <label class="font-bold text-slate-200 block">🔑 WordsAPI Key (Optional):</label>
      <input
        v-model="localSettings.wordsApiKey"
        type="password"
        placeholder="WordsAPI Key..."
        class="w-full bg-dark-muted border border-dark-border rounded-xl px-3 py-2 text-sm text-slate-100 placeholder-slate-500 outline-none focus:border-teal-500 font-mono"
      />
    </div>

    <div class="space-y-2 pt-2 border-t border-dark-border/60">
      <label class="font-bold text-slate-200 block">🔎 Test dictionary connection:</label>
      <div class="grid grid-cols-2 gap-2">
        <button type="button" class="px-2 py-1.5 rounded-lg bg-dark-muted border border-dark-border text-sm font-bold cursor-pointer" :disabled="connectionBusy.free_dictionary" @click="emit('test-dictionary', 'free_dictionary')">Test Free Dictionary</button>
        <button type="button" class="px-2 py-1.5 rounded-lg bg-dark-muted border border-dark-border text-sm font-bold cursor-pointer" :disabled="connectionBusy.wiktionary" @click="emit('test-dictionary', 'wiktionary')">Test Wiktionary</button>
        <button type="button" class="px-2 py-1.5 rounded-lg bg-dark-muted border border-dark-border text-sm font-bold cursor-pointer" :disabled="connectionBusy.merriam_webster" @click="emit('test-dictionary', 'merriam_webster')">Test Merriam-Webster</button>
        <button type="button" class="px-2 py-1.5 rounded-lg bg-dark-muted border border-dark-border text-sm font-bold cursor-pointer" :disabled="connectionBusy.wordnik" @click="emit('test-dictionary', 'wordnik')">Test Wordnik</button>
        <button type="button" class="px-2 py-1.5 rounded-lg bg-dark-muted border border-dark-border text-sm font-bold cursor-pointer" :disabled="connectionBusy.words_api" @click="emit('test-dictionary', 'words_api')">Test WordsAPI</button>
      </div>
      <p class="text-xs text-slate-400">
        {{ connectionStatus[localSettings.dictionaryProvider] || Object.values(connectionStatus).filter((item) => !String(item).startsWith('translation:')).slice(-1)[0] }}
      </p>
    </div>

    <!-- Pronunciation Speech Settings -->
    <div class="space-y-2 pt-2 border-t border-dark-border/60">
      <label class="font-bold text-slate-200 block">🔊 Speech Synthesis Voice (TTS Voice):</label>
      <select
        v-model="localSettings.pronunciationVoiceURI"
        class="w-full bg-dark-muted border border-dark-border text-slate-200 text-sm font-medium rounded-xl px-3 py-2 outline-none focus:border-teal-500 cursor-pointer"
      >
        <option value="">Auto-select system default voice</option>
        <option v-for="voice in availableVoices" :key="voice.voiceURI" :value="voice.voiceURI">
          {{ voice.name }} ({{ voice.lang }})
        </option>
      </select>

      <div class="flex items-center gap-3 pt-1">
        <span class="text-slate-300 font-bold">Speech Rate:</span>
        <input
          type="range"
          v-model.number="localSettings.pronunciationRate"
          min="0.5"
          max="1.5"
          step="0.05"
          class="flex-1 accent-teal-500 cursor-pointer"
        />
        <span class="font-mono text-teal-400 font-bold w-10 text-right">{{ localSettings.pronunciationRate }}x</span>
      </div>
    </div>
  </div>
</template>
